import "@styles/globals.css";
import { Ysabeau_Infant, Roboto_Mono } from "@next/font/google";
import type { Metadata } from "next";
import { Nav } from "@components/Nav";

export const font = Roboto_Mono({
  subsets: ["latin", "cyrillic"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={font.className}>
      <body className="app main">
          <Nav />
          {children}
      </body>
    </html>
  );
}
