import '@styles/globals.css';
import { Ysabeau_Infant } from "@next/font/google"
import type { Metadata } from "next";
import { Nav } from "@components/Nav";

export const quicksand = Ysabeau_Infant({subsets: ['latin', 'cyrillic'], weight: '300'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={quicksand.className}>
      <main className="app main">
        <Nav />
        {children}
      </main>
    </html>
  );
}
